export const PROJECTS = [
  // Tab 0: Full Stack Applications & Websites
  [
    {
      title: "ARS – Auto Repair Response Network Service",
      desc: "🏆 Best Paper Presentation Award Winner (97% score) at the 8th Research Congress. A civic technology solution designed to provide emergency automotive assistance to stranded motorists. This mobile application connects vehicle owners with nearby professional mechanics during roadside emergencies, ensuring rapid response and community safety. Built with Flutter and Firebase using Feature-First Clean Architecture to deliver reliable, life-saving assistance when people need it most.",
      img: "/images/hero/ars.jpg",
      alt: "ARS - Auto Repair Response Network Service interface",
      link: "https://github.com/KpG782/ARSAPPLICATION",
      demoLink: "https://www.facebook.com/photo/?fbid=865808522861853&set=a.129247269851319",
      techStack: [
        "Flutter",
        "Firebase",
        "Dart",
        "Cloud Firestore",
        "Google Maps",
        "Firebase Cloud Messaging",
        "Clean Architecture",
      ],
      category: "Award-Winning Mobile Application",
      members: [
        "Ken Patrick Garcia",
        "Mark Angelo P. Rivera",
        "Exequel Adizon",
        "Chester Magtajas",
      ],
      mentors: [
        "Mr. Rhumel",
        "Mr. Ferdinand",
        "Mr. Ervin",
        "Mr. Paul",
      ],
      features: [
        "Real-time location services and GPS tracking",
        "Service booking with live status tracking",
        "In-app chat between customers and mechanics",
        "Vehicle management system",
        "Push notifications via Firebase Cloud Messaging",
        "Separate dashboards for customers and mechanics",
        "Emergency request system",
        "OSRM routing and navigation",
      ],
      achievements: [
        "🏆 Best Paper Presentation Award - 8th Research Congress",
        "📊 Average Score: 97%",
        "🎓 Recognized by University of Makati",
        "🔬 Center for University Research Award",
      ],
      duration: "6 months",
      status: "In Progress",
    },
    {
      title: "FlowFit – AI-Powered Kids Fitness Companion",
      desc: "🏆 CHAMPIONS at C(Old) (St)art Hackathon 2025 by Old.St Labs. A public health solution addressing childhood obesity and sedentary lifestyles in the digital age. This innovative fitness app helps children (7-12 years old) build lifelong healthy habits through an engaging buddy system where kids nurture a whale pet companion that grows as they drink water, exercise, and eat nutritious food. Built with Flutter and WearOS with local AI inference to make wellness accessible, fun, and meaningful for the next generation.",
      img: "/images/hero/flowfit.jpg",
      alt: "FlowFit - AI-powered kids fitness companion with WearOS",
      link: "https://github.com/KpG782",
      demoLink: "https://www.facebook.com/photo/?fbid=122146790480960452&set=pcb.122146791386960452",
      techStack: [
        "Flutter",
        "Kotlin Native",
        "WearOS",
        "Method Channels",
        "Local AI Inference",
        "Wearable Data Layer",
        "AI Integration",
      ],
      category: "Award-Winning Hackathon Project",
      members: [
        "Jam Emmanuel Villarosa - Team Leader",
        "Ken Patrick Garcia - Backend & WearOS Dev",
        "Exequel Adizon",
        "Mark Siazon",
      ],
      features: [
        "Interactive whale pet companion that grows with healthy habits",
        "WearOS integration for fitness tracking",
        "Flutter method channels with Kotlin Native communication",
        "Local AI inference for food recognition",
        "Wearable data layer synchronization",
        "Gamified health tracking for children",
        "Water intake monitoring",
        "Exercise tracking and encouragement",
      ],
      achievements: [
        "🏆 CHAMPIONS - C(Old) (St)art Hackathon 2025",
        "🎯 5-Day Intensive Hackathon",
        "👶 Pivoted from adult fitness to kids (7-12) on Day 5",
        "🌟 Organized by Old.St Labs",
        "🤝 Mentored by Rob Woodhead (Co-founder)",
      ],
      myRole: "Backend development and WearOS communication implementation using Flutter method channels with Kotlin Native for local inference and wearable data layer communication",
      duration: "5 days",
      status: "Completed",
    },
    {
      title: "Pacebeats – Smart Music Recommender System",
      desc: "🥈 1st Runner Up at InfoTech Olympics 2025 (University of Makati) for Android App Development: Productivity. A wellness-driven productivity innovation that revolutionizes how users optimize their workflow and mental performance. This cutting-edge application leverages biometric data from Samsung Galaxy Watch 6 to deliver personalized music recommendations based on real-time heart rate and inter-beat intervals, creating the perfect auditory environment for peak productivity. Built with Kotlin and Jetpack Compose, PaceBeats transforms wearable technology into an intelligent productivity companion that adapts to your physiological state.",
      img: "/images/hero/pacebeats.jpg",
      alt: "Pacebeats - Award-winning smart heart rate monitoring app",
      link: "https://github.com/KpG782",
      demoLink: "https://www.linkedin.com/feed/update/urn:li:activity:7391489789952212992/",
      techStack: [
        "Kotlin",
        "Jetpack Compose",
        "Samsung Health SDK",
        "Android Studio",
        "MVVM Architecture",
        "Machine Learning/AI",
        "Samsung Galaxy Watch 6",
      ],
      category: "Award-Winning Mobile Application",
      members: [
        "Ken Patrick Garcia - Lead Developer",
        "Timothy Forte - UI/UX Design",
        "Lanz Corpuz - Frontend Mobile Dev",
        "Brian Ashley Papa - ML/AI",
      ],
      features: [
        "Real-time heart rate monitoring",
        "Inter-beat interval analysis",
        "Smart pace detection with AI",
        "Music recommendation system",
        "Galaxy Watch 6 integration",
        "Cross-platform productivity features",
      ],
      achievements: [
        "🥈 1st Runner Up - InfoTech Olympics 2025",
        "🏆 Android App Development: Productivity Category",
        "🎓 University of Makati Competition",
        "🎤 First Pitch Competition Experience",
      ],
      duration: "3 months",
      status: "In Progress",
    },
    {
      title: "HerbaLens – AI-Powered Medicinal Plant Recognition",
      desc: "🏅 TOP 10 FINALISTS out of 53 entries at the 2025 DOST-TAPI Regional Invention Contest and Exhibits (ClustRICE) held at Philippine Science High School. A research-driven Android application that bridges traditional Filipino herbal knowledge with modern AI technology to identify medicinal plants and provide detailed botanical information.",
      img: "/images/hero/herbalens.jpg",
      alt: "HerbaLens - AI medicinal plant recognition app",
      link: "https://theherbalenswebsite.web.app/",
      demoLink: "https://www.linkedin.com/feed/update/urn:li:activity:7363929538734510080/",
      techStack: [
        "Android",
        "Kotlin",
        "Machine Learning",
        "Computer Vision",
        "AI Image Recognition",
        "TensorFlow",
      ],
      category: "Award-Winning Research App",
      members: [
        "Mark Angelo P. Rivera - Team Leader",
        "Ken Patrick Garcia - QA & Data Validation",
        "Paul Xavier Dubiao - Developer",
      ],
      features: [
        "AI-powered medicinal plant identification",
        "Comprehensive plant information database",
        "Image capture and real-time recognition",
        "Traditional Filipino herbal knowledge integration",
        "Quality-assured plant data validation",
      ],
      achievements: [
        "🏅 TOP 10 FINALISTS - ClustRICE 2025",
        "📊 Selected from 53 innovative entries",
        "🔬 DOST-TAPI Regional Invention Contest",
        "🏫 Philippine Science High School Competition",
        "🎓 National Capital Region Cluster",
      ],
      myRole: "Data collection, quality assurance testing, and validation of plant information for accuracy and reliability",
      duration: "4 months",
      status: "Completed",
    },
    {
      title: "LexInSight – AI-Powered Philippine Legal Compliance Assistant",
      desc: "A civic technology solution democratizing access to Philippine legal knowledge and compliance expertise. This intelligent full-stack platform empowers individuals, small businesses, and organizations to navigate complex legal requirements without expensive consultations. By leveraging advanced RAG (Retrieval-Augmented Generation) and conversational AI, LexInSight transforms legal compliance from an intimidating barrier into an accessible resource, promoting justice, transparency, and informed decision-making across Filipino communities. Built to bridge the gap between legal complexity and public understanding.",
      img: "/images/hero/lexinsight.jpg",
      alt: "LexInSight - AI-powered Philippine legal compliance platform",
      link: "https://github.com/KpG782/lexiph",
      demoLink: "https://github.com/KpG782/lexiph",
      techStack: [
        "Next.js 16",
        "React 19",
        "TypeScript",
        "Supabase",
        "PostgreSQL",
        "RAG (Retrieval-Augmented Generation)",
        "Tailwind CSS",
        "Framer Motion",
        "Zustand",
        "Vector Search",
      ],
      category: "Full Stack Application",
      members: [
        "Ken Patrick Garcia - Full Stack Developer",
        "Jam Villarosa - AI/ML Engineer",
        "Mark Siazon - UI/UX Designer",
        "Ashlyn Torres - Project Manager",
      ],
      features: [
        "Dual-mode chat interface (General & Compliance modes)",
        "RAG implementation for advanced document analysis",
        "Multi-document support (up to 3 files, 5MB each)",
        "Real-time AI-powered legal query responses",
        "Automated compliance checking against Philippine laws",
        "Secure document management with enterprise-grade security",
        "Row Level Security (RLS) for data protection",
        "Real-time chat with WebSocket integration",
        "Comprehensive Philippine legal knowledge base",
      ],
      technicalHighlights: [
        "Feature-first architecture with Next.js App Router",
        "RAG (Retrieval-Augmented Generation) for intelligent document analysis",
        "Agentic AI with vector search and semantic retrieval",
        "Full-stack TypeScript implementation",
        "Supabase backend with PostgreSQL database",
        "Row Level Security for multi-tenant data isolation",
        "Real-time updates and WebSocket communication",
        "State management with Zustand",
        "Responsive design with Tailwind CSS",
      ],
      myRole: "Full-stack development including frontend (Next.js, React, TypeScript), backend integration (Supabase, API design), database architecture, state management, and performance optimization. Implemented core RAG functionality and real-time chat features.",
      duration: "3 months",
      status: "In Progress (Beta)",
    },
    {
      title: "CampusCare – Student Wellness Platform",
      desc: "A mental health innovation addressing the critical student wellness crisis in Philippine universities. This mobile-first platform breaks down barriers to mental health support by providing University of Makati students with immediate access to professional guidance counseling services. With AI-powered mood analysis using DistilBERT, real-time counselor chat, and seamless appointment booking, CampusCare transforms mental health care from reactive to proactive, ensuring students receive timely support during their most vulnerable moments. Built to destigmatize mental health and make wellness resources accessible to every student.",
      img: "/images/projects/project1/2.png",
      alt: "CampusCare - Student wellness platform screenshot",
      link: "https://github.com/KpG782/CampusCare",
      demoLink:
        "https://drive.google.com/drive/folders/1RcX2Sduq-87-wtzQmxIjrcNhyXWUNMeN?usp=sharing",
      techStack: [
        "Flutter",
        "Firebase",
        "Dart",
        "Cloud Firestore",
        "DistilBERT AI",
      ],
      category: "Mobile Application",
      members: [
        "Ken Garcia",
        "Mars Maguddayao",
        "Timothy Forte",
        "Lanz Corpuz",
        "Brian Ashley",
      ],
      features: [
        "AI-powered mood analysis using DistilBERT",
        "Real-time chat with counselors",
        "Appointment booking system",
        "Secure authentication and user management",
      ],
      duration: "3 months",
      status: "Completed",
    },
  ],
  // Tab 1: Sample Full Stack Design for Clients
  [
    {
      title: "Pacebeats Landing Page",
      desc: "Modern running app showcase built with Astro and TailwindCSS, featuring heart rate monitoring and pace tracking for runners with Samsung Health SDK integration.",
      img: "/images/projects/project2/1.jpg",
      alt: "Pacebeats landing page - Modern running app showcase",
      link: "https://github.com/KpG782/Pacebeats-landing-page",
      demoLink: "https://pacebeats.top",
      techStack: ["Astro", "TailwindCSS", "TypeScript"],
      category: "Landing Page",
      members: [
        "Ken Patrick Garcia",
        "Timothy Forte",
        "Brian Ashley Papa",
        "Lanz Corpuz",
      ],
      features: [
        "Responsive design",
        "Interactive sections",
        "Fast performance with Astro SSG",
        "Conversion focused CTAs",
      ],
      duration: "2 months",
      status: "Completed",
    },
    {
      title: "Designers' Cafe Website",
      desc: "Digital showcase for a creative coffee shop in Pembo, Taguig, featuring interactive menu, gallery, and community-focused design atmosphere.",
      img: "/images/projects/project2/2.png",
      alt: "Designers' Cafe website interface",
      link: "https://github.com/KpG782/designers-cafe",
      demoLink: "https://designers-cafe.vercel.app",
      techStack: ["Astro", "TailwindCSS", "JavaScript", "Google Maps API"],
      category: "Business Website",
      members: ["Ken Patrick Garcia"],
      features: [
        "Interactive menu system",
        "3D barista profiles",
        "Google Maps integration",
        "Responsive gallery",
      ],
      duration: "1.5 months",
      status: "Delivered",
    },
    {
      title: "Tugang Cafe Website",
      desc: "Premium coffee shop website with custom cursor animations, ultrawide support, and engaging scroll animations showcasing togetherness and community.",
      img: "/images/projects/project2/3.png",
      alt: "Tugang Cafe website with coffee-themed design",
      link: "https://github.com/KpG782/tugang-cafe",
      demoLink: "https://tugang-cafe.vercel.app",
      techStack: [
        "Astro",
        "TailwindCSS",
        "Intersection Observer",
        "Custom CSS",
      ],
      category: "Business Website",
      members: ["Ken Patrick Garcia"],
      features: [
        "Custom coffee cursor animation",
        "Scroll animations with Intersection Observer",
        "Interactive menu modals",
        "Ultrawide screen support",
      ],
      duration: "1 month",
      status: "Delivered",
    },
    {
      title: "Wedding Template Collection 1",
      desc: "Modern, elegant, and accessible wedding website templates featuring countdown timers, RSVP integration, and beautiful storytelling animations.",
      img: "/images/projects/project2/4.png",
      alt: "Wedding template with elegant design and animations",
      link: "https://github.com/KpG782/WeddingTemplate1",
      demoLink: "https://wedding-template2-one.vercel.app",
      techStack: ["HTML5", "TailwindCSS", "Animate.css", "JavaScript"],
      category: "Template Design",
      members: ["Ken Patrick Garcia", "Aby Ann Avinante"],
      features: [
        "Interactive countdown timer",
        "RSVP form integration",
        "Spotify playlist embed",
        "QR code gift registry",
      ],
      duration: "3 weeks",
      status: "Completed",
    },
    {
      title: "Wedding Template Collection 2",
      desc: "Modern, elegant, and accessible wedding website templates featuring countdown timers, RSVP integration, and beautiful storytelling animations.",
      img: "/images/projects/project2/5.png",
      alt: "Wedding template with elegant design and animations",
      link: "https://github.com/KpG782/WeddingTemplate1",
      demoLink: "https://wedding-template2-one.vercel.app",
      techStack: ["HTML5", "TailwindCSS", "Animate.css", "JavaScript"],
      category: "Template Design",
      members: ["Ken Patrick Garcia", "Aby Ann Avinante"],
      features: [
        "Interactive countdown timer",
        "RSVP form integration",
        "Spotify playlist embed",
        "QR code gift registry",
      ],
      duration: "3 weeks",
      status: "Completed",
    },
    {
      title: "JASM Printing Services",
      desc: "Business website for local printing services in Pasig, showcasing apparel printing, ID cards, labels, and event giveaways with responsive design.",
      img: "/images/projects/project2/6.png",
      alt: "JASM Printing Services business website",
      link: "https://github.com/KpG782/JASMPrinting",
      demoLink: "https://jasm-printing.vercel.app",
      techStack: ["HTML5", "CSS3", "JavaScript", "Font Awesome"],
      category: "Business Website",
      members: [
        "Timothy Forte",
        "Ken Garcia",
        "Lanz Corpuz",
        "Mars Maguddayao",
        "Brian Ashley",
      ],
      features: [
        "Product catalog showcase",
        "Contact forms",
        "Service showcase sections",
        "Mobile-first design approach",
      ],
      duration: "6 weeks",
      status: "Delivered",
    },
    {
      title: "Hungry Potter's Tapsilogan",
      desc: "Student-friendly silog restaurant website with responsive menu display, built with Bootstrap 5 and modern CSS for local Filipino dining.",
      img: "/images/projects/project2/7.png",
      alt: "Hungry Potter's restaurant website interface",
      link: "https://github.com/KpG782/HungryPotters",
      demoLink: "https://hungry-potters.vercel.app",
      techStack: ["HTML5", "Bootstrap 5", "CSS3", "JavaScript"],
      category: "Restaurant Website",
      members: [
        "Ken Patrick Garcia",
        "Mars Maguddayao",
        "Timothy Forte",
        "Lanz Corpuz",
        "Ejay Buscato",
      ],
      features: [
        "Responsive menu display",
        "Bootstrap 5 components",
        "Image carousel for dishes",
        "Contact information integration",
      ],
      duration: "4 weeks",
      status: "Completed",
    },
  ],
  // Tab 2: Frontend Development
  [
    {
      title: "Interactive Portfolio with Three.js",
      desc: "Showcase of advanced frontend skills with 3D graphics, animations, and modern web technologies. Features immersive 3D scenes and smooth scroll-based interactions.",
      img: "/images/projects/project1/4.png",
      alt: "Interactive 3D portfolio website",
      link: "https://github.com/KpG782/3D_Portfolio",
      demoLink: "https://3-d-portfolio-eight-pi.vercel.app",
      techStack: ["React", "Three.js", "GSAP", "Vite", "TailwindCSS"],
      category: "Frontend Showcase",
      members: ["Ken Patrick Garcia"],
      features: [
        "3D scene rendering with Three.js",
        "GSAP scroll animations",
        "Responsive 3D design",
        "Performance optimized",
      ],
      duration: "1 month",
      status: "Completed",
    },
    {
      title: "Responsive Landing Page Design",
      desc: "Modern landing page built with cutting-edge frontend technologies, featuring smooth animations, micro-interactions, and pixel-perfect responsive design.",
      img: "/images/projects/project2/1.jpg",
      alt: "Responsive landing page with modern design",
      link: "https://github.com/KpG782/Pacebeats-landing-page",
      demoLink: "https://pacebeats.top",
      techStack: ["Astro", "TailwindCSS", "TypeScript", "CSS Grid"],
      category: "Frontend Challenge",
      members: ["Ken Patrick Garcia"],
      features: [
        "Mobile-first responsive design",
        "CSS Grid and Flexbox layouts",
        "Optimized performance",
        "Accessible UI components",
      ],
      duration: "2 weeks",
      status: "Completed",
    },
    {
      title: "Modern UI Components Library",
      desc: "Collection of reusable UI components built with modern CSS and JavaScript, featuring animations, transitions, and interactive elements.",
      img: "/images/projects/project2/2.png",
      alt: "UI components library showcase",
      link: "https://github.com/KpG782/designers-cafe",
      demoLink: "https://designers-cafe.vercel.app",
      techStack: ["HTML5", "CSS3", "JavaScript", "TailwindCSS"],
      category: "UI/UX Design",
      members: ["Ken Patrick Garcia"],
      features: [
        "Reusable component system",
        "Smooth CSS transitions",
        "Interactive hover effects",
        "Cross-browser compatible",
      ],
      duration: "3 weeks",
      status: "Completed",
    },
  ],
  // Tab 3: Other Projects
  [
    {
      title: "Mathematical Algorithms Visualizer",
      desc: "Educational tool for visualizing mathematical sequences and algorithms. Built with Flutter to demonstrate complex mathematical concepts in an interactive way.",
      img: "/images/projects/project1/6.png",
      alt: "Mathematical algorithms visualization",
      link: "https://github.com/KpG782/SeqSense",
      demoLink: "#",
      techStack: ["Flutter", "Dart", "Custom Algorithms"],
      category: "Educational Tool",
      members: ["Ken Patrick Garcia", "Brian Ashley Papa", "Mars Maguddayao"],
      features: [
        "Fibonacci sequence calculator",
        "Lucas numbers visualization",
        "Collatz conjecture explorer",
        "Pascal's triangle generator",
      ],
      duration: "1.5 months",
      status: "Completed",
    },
    {
      title: "Movie Database Browser",
      desc: "Cross-platform movie browsing application demonstrating API integration and mobile development skills with React Native.",
      img: "/images/projects/project1/3.png",
      alt: "Movie database browser app",
      link: "https://github.com/KpG782/MovieFlix-React",
      demoLink: "#",
      techStack: ["React Native", "Expo", "TMDB API", "AsyncStorage"],
      category: "Utility App",
      members: ["Ken Patrick Garcia"],
      features: [
        "TMDB API integration",
        "Search and filter movies",
        "Save favorite movies",
        "Cross-platform support (iOS & Android)",
      ],
      duration: "Ongoing",
      status: "In Progress",
    },
    {
      title: "Custom Cursor & Animation Library",
      desc: "Collection of custom cursors and micro-animations for web projects, demonstrating advanced CSS and JavaScript animation techniques.",
      img: "/images/projects/project2/3.png",
      alt: "Custom cursor animations showcase",
      link: "https://github.com/KpG782/tugang-cafe",
      demoLink: "https://tugang-cafe.vercel.app",
      techStack: ["JavaScript", "CSS3", "Intersection Observer API"],
      category: "Animation Library",
      members: ["Ken Patrick Garcia"],
      features: [
        "Custom cursor animations",
        "Scroll-triggered effects",
        "Intersection Observer implementation",
        "Performance optimized animations",
      ],
      duration: "2 weeks",
      status: "Completed",
    },
    {
      title: "Bootstrap Component Showcase",
      desc: "Demonstration of Bootstrap 5 capabilities through a complete restaurant website, showcasing responsive components and modern layout techniques.",
      img: "/images/projects/project2/7.png",
      alt: "Bootstrap components showcase",
      link: "https://github.com/KpG782/HungryPotters",
      demoLink: "https://hungry-potters.vercel.app",
      techStack: ["Bootstrap 5", "HTML5", "CSS3", "JavaScript"],
      category: "Framework Demo",
      members: [
        "Ken Patrick Garcia",
        "Mars Maguddayao",
        "Timothy Forte",
        "Lanz Corpuz",
        "Ejay Buscato",
      ],
      features: [
        "Bootstrap 5 grid system",
        "Responsive navigation",
        "Card components",
        "Modal implementations",
      ],
      duration: "4 weeks",
      status: "Completed",
    },
  ],
];
